language: cpp
dist: bionic

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:mutlaqja/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install libnova-dev libcfitsio-dev libusb-1.0-0-dev zlib1g-dev libgsl-dev libjpeg-dev libcurl4-gnutls-dev libtiff-dev libfftw3-dev libftdi-dev libgps-dev libraw-dev libdc1394-22-dev libgphoto2-dev libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev libftdi1-dev libavcodec-dev libavdevice-dev  libopencv-dev software-properties-common indi-full gsc libindi-dev cimg-dev

before_script:
  - cd
  - git clone  https://github.com/gehelem/indi_hic_agent.git
  - cd indi_hic_agent
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..

script:
  # once CMake has done its job we just build using make as usual
  - make
  # if the project uses ctest we can run the tests like this
  #- make test

