#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define HICFOCUSAGENT_VERSION_MAJOR @HICFOCUSAGENT_VERSION_MAJOR@
#define HICFOCUSAGENT_VERSION_MINOR @HICFOCUSAGENT_VERSION_MINOR@

#endif // CONFIG_H
